apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yqej1f4lk-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yqej1f4lk-dotnet-basic-gitops